#ifndef CONFIGINTERFACE_GLOBAL_H
#define CONFIGINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGINTERFACE_LIBRARY)
#  define CONFIGINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGINTERFACE_GLOBAL_H
