#ifndef EXCELOPERATE_GLOBAL_H
#define EXCELOPERATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXCELOPERATE_LIBRARY)
#  define EXCELOPERATESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXCELOPERATESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXCELOPERATE_GLOBAL_H
